name: CI/CD for Flask Backend

on:
  push:
    branches:
      - main  # CI/CD wird ausgelöst, wenn in den main-Branch gepusht wird

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      # Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Tests ausführen
      #- name: Run tests
       # run: pytest

      # Deployment auf Heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a cinephoria-backend
          git push heroku main -f
